max_radius: 10.0
min_radius: 3.0
sampling_angle_deg: 10
max_sampling_angle_deg: 50
max_planning_distance: 55.0
replanning_distance: 5.0
replanning_freq: 10.0
distance_from_start_value: 3.0
self.distance_to_goal_value: 5.0
self.max_radius_value: 18.0