# sets maximal velocity and acceleration values along the trajectory
dynamic_params: {
  max_v: 5.0,
  max_a: 2.0
}

waypoints:
  # your waypoints here. Think about how to best add any number of waypoints
  # and the according velocity and acceleration constraints.

  # round 1
  #- [ -38.06, 10.0, 7.5, 3.2, 0, 0 ]
  - [ -150.0, 9.0, 14.0, 3.2, -1, -1 ]
  - [ -200.2, 8.0, 17.0, 3.0, -1, -1 ]
  - [ -322.0, 7.0, 20, 3.0, -1, -1]


